### ISSUE TITLE
Additional comments on the book provided by Nicolai to be addressed

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQI-Book#58]
Description:
-------------

**needed now**
- [x]  I also reviewed Chapter 02, 03, quickly. Seems similar ot the notebook with some exceptions in chapter 03. 
We need to at least avoid the repetition there. (note by @amal-ghamdi , done in #47)

- [x] Also pre-running these notebooks would be  tremendeously useful I think. (note by @amal-ghamdi, I believe everything now is executed)
- [x] Rendering of equations need to be fixed (#72)
- [x] printing sampling progress needs to be fixed (this should be fixed after using the new samplers #54 #55 , tqdm will be used)
- [x] printing all samples in Samples object need to re-considered. Takes up too much space. (comment by @amal-ghamdi , can fix now by suppressing output, e.g. storing samples in a variable) (seems to be issue for only one case, toward the end of Gibbs notebook , fixed in #72, by storing the samples in a variable)
- [x] Some references to "the uqcourse" need to be at least clarified if one reads the book outside that scope (comment by @amal-ghamdi , removed as part of #47 and #72)
- [x] installation and running sections updated (comment by @amal-ghamdi , done in #47 and in #72)
- [x] ### How to run the code and solve the coding exercises in this mini-book? This section (and below) needs an update. (comment by @amal-ghamdi , done in #47 and #72)
- [x] short intro for the simplest BIP added (comment by @amal-ghamdi added for the short version )
- [x] Some learning objectives should be updated after this reorganizing (yes, chapter 1 learning objectives and distribution notebook learning objectives were updated #47 #72)

**easy**

**could wait** (moved to #73)
- ~Perhaps this is personal preferance, but I was thinking perhaps the convolution forward model should be explained first rather than the heat equation.~

**delegated to other issues**
- In my review the Gibbs notebook needs a serious update. The rest look like they are in a good state. #55 
- links to sections in notebooks should be fixed. At least I can't get them to work. (comment by @amal-ghamdi , I could not find a solution for this issue yet #67, only navigation menu on the right works )

DoD:
------

- [ ] The comments from @nabriis above in the description are addressed
- [ ] The updates are reviewed and merged

Notes:
--------
This is the issue content before processing (no need to look at this section, it is processed and rewritten above)

Copied comments from @nabriis from #52

```
Context of review. Chapter 1 + Chapters A+B.

I like the structure established. Happy to update any notebook needed for the training.

In my review the Gibbs notebook needs a serious update. The rest look like they are in a good state.

I also reviewed Chapter 02, 03, quickly. Seems similar ot the notebook with some exceptions in chapter 03. 
We need to at least avoid the repetition there.

Comments
I added some comments on some sections that need update. We need to update either in this PR or create
issue to deal with it. Perhaps this is personal preferance, but I was thinking perhaps the convolution forward
model should be explained first rather than the heat equation. Also pre-running these notebooks would be 
tremendeously useful I think.
```
Additional comments from @nabriis 
```
1) Rendering of equations need to be fixed
2) printing sampling progress needs to be fixed
3) printing all samples in Samples object need to re-considered. Takes up too much space.
4) Some learning objectives should be updated after this reorganizing
5) Some references to "the uqcourse" need to be at least clarified if one reads the book outside that scope
6) links to sections in notebooks should be fixed. At least I can't  get them to work.
```

**Comment by amal-ghamdi** [comment]
@jakobsj, would you please review the DoD, I organized the comments from @nabriis into three groups. The top group I would like to address today along with #53 in one PR. Also feel free to suggest moving the comments along the sections (needed now, easy, can wait)
Thank you.

**Comment by jakobsj** [comment]
@amal-ghamdi approved.

**Comment by amal-ghamdi** [comment]
@jakobsj , DoD updated in the sense that remaining issues were moved to #73, as per our discussion this morning
